window.mockofun_its_emojis = [
{"name":"Heart With Arrow","emoji":"💘"},
{"name":"Heart With Ribbon","emoji":"💝"},
{"name":"Sparkling Heart","emoji":"💖"},
{"name":"Growing Heart","emoji":"💗"},
{"name":"Beating Heart","emoji":"💓"},
{"name":"Revolving Hearts","emoji":"💞"},
{"name":"Two Hearts","emoji":"💕"},
{"name":"Heart Decoration","emoji":"💟"},
{"name":"Heart Exclamation","emoji":"❣"},
{"name":"Broken Heart","emoji":"💔"},
{"name":"Red Heart","emoji":"❤"},
{"name":"Orange Heart","emoji":"🧡"},
{"name":"Yellow Heart","emoji":"💛"},
{"name":"Green Heart","emoji":"💚"},
{"name":"Blue Heart","emoji":"💙"},
{"name":"Purple Heart","emoji":"💜"},
{"name":"Black Heart","emoji":"🖤"},
{"name":"Hundred Points","emoji":"💯"},
{"name":"Anger Symbol","emoji":"💢"},
{"name":"Speech Balloon","emoji":"💬"},
{"name":"Eye in Speech Bubble","emoji":"👁️‍🗨️"},
{"name":"Right Anger Bubble","emoji":"🗯"},
{"name":"Thought Balloon","emoji":"💭"},
{"name":"Zzz","emoji":"💤"},
{"name":"White Flower","emoji":"💮"},
{"name":"Hot Springs","emoji":"♨"},
{"name":"Barber Pole","emoji":"💈"},
{"name":"Stop Sign","emoji":"🛑"},
{"name":"Twelve O’Clock","emoji":"🕛"},
{"name":"Twelve-Thirty","emoji":"🕧"},
{"name":"One O’Clock","emoji":"🕐"},
{"name":"One-Thirty","emoji":"🕜"},
{"name":"Two O’Clock","emoji":"🕑"},
{"name":"Two-Thirty","emoji":"🕝"},
{"name":"Three O’Clock","emoji":"🕒"},
{"name":"Three-Thirty","emoji":"🕞"},
{"name":"Four O’Clock","emoji":"🕓"},
{"name":"Four-Thirty","emoji":"🕟"},
{"name":"Five O’Clock","emoji":"🕔"},
{"name":"Five-Thirty","emoji":"🕠"},
{"name":"Six O’Clock","emoji":"🕕"},
{"name":"Six-Thirty","emoji":"🕡"},
{"name":"Seven O’Clock","emoji":"🕖"},
{"name":"Seven-Thirty","emoji":"🕢"},
{"name":"Eight O’Clock","emoji":"🕗"},
{"name":"Eight-Thirty","emoji":"🕣"},
{"name":"Nine O’Clock","emoji":"🕘"},
{"name":"Nine-Thirty","emoji":"🕤"},
{"name":"Ten O’Clock","emoji":"🕙"},
{"name":"Ten-Thirty","emoji":"🕥"},
{"name":"Eleven O’Clock","emoji":"🕚"},
{"name":"Eleven-Thirty","emoji":"🕦"},
{"name":"Cyclone","emoji":"🌀"},
{"name":"Spade Suit","emoji":"♠"},
{"name":"Heart Suit","emoji":"♥"},
{"name":"Diamond Suit","emoji":"♦"},
{"name":"Club Suit","emoji":"♣"},
{"name":"Joker","emoji":"🃏"},
{"name":"Mahjong Red Dragon","emoji":"🀄"},
{"name":"Flower Playing Cards","emoji":"🎴"},
{"name":"Muted Speaker","emoji":"🔇"},
{"name":"Speaker Low Volume","emoji":"🔈"},
{"name":"Speaker Medium Volume","emoji":"🔉"},
{"name":"Speaker High Volume","emoji":"🔊"},
{"name":"Loudspeaker","emoji":"📢"},
{"name":"Megaphone","emoji":"📣"},
{"name":"Postal Horn","emoji":"📯"},
{"name":"Bell","emoji":"🔔"},
{"name":"Bell With Slash","emoji":"🔕"},
{"name":"Musical Note","emoji":"🎵"},
{"name":"Musical Notes","emoji":"🎶"},
{"name":"ATM Sign","emoji":"🏧"},
{"name":"Litter in Bin Sign","emoji":"🚮"},
{"name":"Potable Water","emoji":"🚰"},
{"name":"Wheelchair Symbol","emoji":"♿"},
{"name":"Men’s Room","emoji":"🚹"},
{"name":"Women’s Room","emoji":"🚺"},
{"name":"Restroom","emoji":"🚻"},
{"name":"Baby Symbol","emoji":"🚼"},
{"name":"Water Closet","emoji":"🚾"},
{"name":"Warning","emoji":"⚠"},
{"name":"Children Crossing","emoji":"🚸"},
{"name":"No Entry","emoji":"⛔"},
{"name":"Prohibited","emoji":"🚫"},
{"name":"No Bicycles","emoji":"🚳"},
{"name":"No Smoking","emoji":"🚭"},
{"name":"No Littering","emoji":"🚯"},
{"name":"Non-Potable Water","emoji":"🚱"},
{"name":"No Pedestrians","emoji":"🚷"},
{"name":"No One Under Eighteen","emoji":"🔞"},
{"name":"Radioactive","emoji":"☢"},
{"name":"Biohazard","emoji":"☣"},
{"name":"Up Arrow","emoji":"⬆"},
{"name":"Up-Right Arrow","emoji":"↗"},
{"name":"Right Arrow","emoji":"➡"},
{"name":"Down-Right Arrow","emoji":"↘"},
{"name":"Down Arrow","emoji":"⬇"},
{"name":"Down-Left Arrow","emoji":"↙"},
{"name":"Left Arrow","emoji":"⬅"},
{"name":"Up-Left Arrow","emoji":"↖"},
{"name":"Up-Down Arrow","emoji":"↕"},
{"name":"Left-Right Arrow","emoji":"↔"},
{"name":"Right Arrow Curving Left","emoji":"↩"},
{"name":"Left Arrow Curving Right","emoji":"↪"},
{"name":"Right Arrow Curving Up","emoji":"⤴"},
{"name":"Right Arrow Curving Down","emoji":"⤵"},
{"name":"Clockwise Vertical Arrows","emoji":"🔃"},
{"name":"Counterclockwise Arrows Button","emoji":"🔄"},
{"name":"Back Arrow","emoji":"🔙"},
{"name":"End Arrow","emoji":"🔚"},
{"name":"On! Arrow","emoji":"🔛"},
{"name":"Soon Arrow","emoji":"🔜"},
{"name":"Top Arrow","emoji":"🔝"},
{"name":"Place of Worship","emoji":"🛐"},
{"name":"Atom Symbol","emoji":"⚛"},
{"name":"Om","emoji":"🕉"},
{"name":"Star of David","emoji":"✡"},
{"name":"Wheel of Dharma","emoji":"☸"},
{"name":"Yin Yang","emoji":"☯"},
{"name":"Latin Cross","emoji":"✝"},
{"name":"Orthodox Cross","emoji":"☦"},
{"name":"Star and Crescent","emoji":"☪"},
{"name":"Peace Symbol","emoji":"☮"},
{"name":"Menorah","emoji":"🕎"},
{"name":"Dotted Six-Pointed Star","emoji":"🔯"},
{"name":"Aries","emoji":"♈"},
{"name":"Taurus","emoji":"♉"},
{"name":"Gemini","emoji":"♊"},
{"name":"Cancer","emoji":"♋"},
{"name":"Leo","emoji":"♌"},
{"name":"Virgo","emoji":"♍"},
{"name":"Libra","emoji":"♎"},
{"name":"Scorpio","emoji":"♏"},
{"name":"Sagittarius","emoji":"♐"},
{"name":"Capricorn","emoji":"♑"},
{"name":"Aquarius","emoji":"♒"},
{"name":"Pisces","emoji":"♓"},
{"name":"Ophiuchus","emoji":"⛎"},
{"name":"Shuffle Tracks Button","emoji":"🔀"},
{"name":"Repeat Button","emoji":"🔁"},
{"name":"Repeat Single Button","emoji":"🔂"},
{"name":"Play Button","emoji":"▶"},
{"name":"Fast-Forward Button","emoji":"⏩"},
{"name":"Reverse Button","emoji":"◀"},
{"name":"Fast Reverse Button","emoji":"⏪"},
{"name":"Upwards Button","emoji":"🔼"},
{"name":"Fast Up Button","emoji":"⏫"},
{"name":"Downwards Button","emoji":"🔽"},
{"name":"Fast Down Button","emoji":"⏬"},
{"name":"Stop Button","emoji":"⏹"},
{"name":"Eject Button","emoji":"⏏"},
{"name":"Cinema","emoji":"🎦"},
{"name":"Dim Button","emoji":"🔅"},
{"name":"Bright Button","emoji":"🔆"},
{"name":"Antenna Bars","emoji":"📶"},
{"name":"Vibration Mode","emoji":"📳"},
{"name":"Mobile Phone Off","emoji":"📴"},
{"name":"Infinity","emoji":"♾"},
{"name":"Recycling Symbol","emoji":"♻"},
{"name":"Trident Emblem","emoji":"🔱"},
{"name":"Name Badge","emoji":"📛"},
{"name":"Japanese Symbol for Beginner","emoji":"🔰"},
{"name":"Hollow Red Circle","emoji":"⭕"},
{"name":"Check Mark Button","emoji":"✅"},
{"name":"Check Box With Check","emoji":"☑"},
{"name":"Check Mark","emoji":"✔"},
{"name":"Multiplication Sign","emoji":"✖"},
{"name":"Cross Mark","emoji":"❌"},
{"name":"Cross Mark Button","emoji":"❎"},
{"name":"Plus Sign","emoji":"➕"},
{"name":"Minus Sign","emoji":"➖"},
{"name":"Division Sign","emoji":"➗"},
{"name":"Curly Loop","emoji":"➰"},
{"name":"Double Curly Loop","emoji":"➿"},
{"name":"Part Alternation Mark","emoji":"〽"},
{"name":"Eight-Spoked Asterisk","emoji":"✳"},
{"name":"Eight-Pointed Star","emoji":"✴"},
{"name":"Sparkle","emoji":"❇"},
{"name":"Double Exclamation Mark","emoji":"‼"},
{"name":"Exclamation Question Mark","emoji":"⁉"},
{"name":"Question Mark","emoji":"❓"},
{"name":"White Question Mark","emoji":"❔"},
{"name":"White Exclamation Mark","emoji":"❕"},
{"name":"Exclamation Mark","emoji":"❗"},
{"name":"Copyright","emoji":"©"},
{"name":"Registered","emoji":"®"},
{"name":"Trade Mark","emoji":"™"},
{"name":"Keycap Number Sign","emoji":"#️⃣"},
{"name":"Keycap Digit Zero","emoji":"0️⃣"},
{"name":"Keycap Digit One","emoji":"1️⃣"},
{"name":"Keycap Digit Two","emoji":"2️⃣"},
{"name":"Keycap Digit Three","emoji":"3️⃣"},
{"name":"Keycap Digit Four","emoji":"4️⃣"},
{"name":"Keycap Digit Five","emoji":"5️⃣"},
{"name":"Keycap Digit Six","emoji":"6️⃣"},
{"name":"Keycap Digit Seven","emoji":"7️⃣"},
{"name":"Keycap Digit Eight","emoji":"8️⃣"},
{"name":"Keycap Digit Nine","emoji":"9️⃣"},
{"name":"Keycap: 10","emoji":"🔟"},
{"name":"Input Latin Uppercase","emoji":"🔠"},
{"name":"Input Latin Lowercase","emoji":"🔡"},
{"name":"Input Numbers","emoji":"🔢"},
{"name":"Input Symbols","emoji":"🔣"},
{"name":"Input Latin Letters","emoji":"🔤"},
{"name":"A Button (Blood Type)","emoji":"🅰"},
{"name":"AB Button (Blood Type)","emoji":"🆎"},
{"name":"B Button (Blood Type)","emoji":"🅱"},
{"name":"CL Button","emoji":"🆑"},
{"name":"Cool Button","emoji":"🆒"},
{"name":"Free Button","emoji":"🆓"},
{"name":"Information","emoji":"ℹ"},
{"name":"ID Button","emoji":"🆔"},
{"name":"Circled M","emoji":"Ⓜ"},
{"name":"New Button","emoji":"🆕"},
{"name":"NG Button","emoji":"🆖"},
{"name":"O Button (Blood Type)","emoji":"🅾"},
{"name":"OK Button","emoji":"🆗"},
{"name":"P Button","emoji":"🅿"},
{"name":"SOS Button","emoji":"🆘"},
{"name":"Up! Button","emoji":"🆙"},
{"name":"Vs Button","emoji":"🆚"},
{"name":"Japanese “Here” Button","emoji":"🈁"},
{"name":"Japanese “Service Charge” Button","emoji":"🈂"},
{"name":"Japanese “Monthly Amount” Button","emoji":"🈷"},
{"name":"Japanese “Not Free of Charge” Button","emoji":"🈶"},
{"name":"Japanese “Reserved” Button","emoji":"🈯"},
{"name":"Japanese “Bargain” Button","emoji":"🉐"},
{"name":"Japanese “Discount” Button","emoji":"🈹"},
{"name":"Japanese “Free of Charge” Button","emoji":"🈚"},
{"name":"Japanese “Prohibited” Button","emoji":"🈲"},
{"name":"Japanese “Acceptable” Button","emoji":"🉑"},
{"name":"Japanese “Application” Button","emoji":"🈸"},
{"name":"Japanese “Passing Grade” Button","emoji":"🈴"},
{"name":"Japanese “Vacancy” Button","emoji":"🈳"},
{"name":"Japanese “Congratulations” Button","emoji":"㊗"},
{"name":"Japanese “Secret” Button","emoji":"㊙"},
{"name":"Japanese “Open for Business” Button","emoji":"🈺"},
{"name":"Japanese “No Vacancy” Button","emoji":"🈵"},
{"name":"Red Circle","emoji":"🔴"},
{"name":"Blue Circle","emoji":"🔵"},
{"name":"Black Circle","emoji":"⚫"},
{"name":"White Circle","emoji":"⚪"},
{"name":"Black Large Square","emoji":"⬛"},
{"name":"White Large Square","emoji":"⬜"},
{"name":"Black Medium Square","emoji":"◼"},
{"name":"White Medium Square","emoji":"◻"},
{"name":"Black Medium-Small Square","emoji":"◾"},
{"name":"White Medium-Small Square","emoji":"◽"},
{"name":"Black Small Square","emoji":"▪"},
{"name":"White Small Square","emoji":"▫"},
{"name":"Large Orange Diamond","emoji":"🔶"},
{"name":"Large Blue Diamond","emoji":"🔷"},
{"name":"Small Orange Diamond","emoji":"🔸"},
{"name":"Small Blue Diamond","emoji":"🔹"},
{"name":"Red Triangle Pointed Up","emoji":"🔺"},
{"name":"Red Triangle Pointed Down","emoji":"🔻"},
{"name":"Diamond With a Dot","emoji":"💠"},
{"name":"White Square Button","emoji":"🔳"},
{"name":"Black Square Button","emoji":"🔲"},
{"name":"Grinning Face","emoji":"😀"},
{"name":"Grinning Face With Big Eyes","emoji":"😃"},
{"name":"Grinning Face With Smiling Eyes","emoji":"😄"},
{"name":"Beaming Face With Smiling Eyes","emoji":"😁"},
{"name":"Grinning Squinting Face","emoji":"😆"},
{"name":"Grinning Face With Sweat","emoji":"😅"},
{"name":"Rolling on the Floor Laughing","emoji":"🤣"},
{"name":"Face With Tears of Joy","emoji":"😂"},
{"name":"Slightly Smiling Face","emoji":"🙂"},
{"name":"Upside-Down Face","emoji":"🙃"},
{"name":"Winking Face","emoji":"😉"},
{"name":"Smiling Face With Smiling Eyes","emoji":"😊"},
{"name":"Smiling Face With Halo","emoji":"😇"},
{"name":"Smiling Face With Hearts","emoji":"🥰"},
{"name":"Smiling Face With Heart-Eyes","emoji":"😍"},
{"name":"Star-Struck","emoji":"🤩"},
{"name":"Face Blowing a Kiss","emoji":"😘"},
{"name":"Kissing Face","emoji":"😗"},
{"name":"Smiling Face","emoji":"☺"},
{"name":"Kissing Face With Closed Eyes","emoji":"😚"},
{"name":"Kissing Face With Smiling Eyes","emoji":"😙"},
{"name":"Face Savoring Food","emoji":"😋"},
{"name":"Face With Tongue","emoji":"😛"},
{"name":"Winking Face With Tongue","emoji":"😜"},
{"name":"Zany Face","emoji":"🤪"},
{"name":"Squinting Face With Tongue","emoji":"😝"},
{"name":"Money-Mouth Face","emoji":"🤑"},
{"name":"Hugging Face","emoji":"🤗"},
{"name":"Face With Hand Over Mouth","emoji":"🤭"},
{"name":"Shushing Face","emoji":"🤫"},
{"name":"Thinking Face","emoji":"🤔"},
{"name":"Zipper-Mouth Face","emoji":"🤐"},
{"name":"Face With Raised Eyebrow","emoji":"🤨"},
{"name":"Neutral Face","emoji":"😐"},
{"name":"Expressionless Face","emoji":"😑"},
{"name":"Face Without Mouth","emoji":"😶"},
{"name":"Smirking Face","emoji":"😏"},
{"name":"Unamused Face","emoji":"😒"},
{"name":"Face With Rolling Eyes","emoji":"🙄"},
{"name":"Grimacing Face","emoji":"😬"},
{"name":"Lying Face","emoji":"🤥"},
{"name":"Relieved Face","emoji":"😌"},
{"name":"Pensive Face","emoji":"😔"},
{"name":"Sleepy Face","emoji":"😪"},
{"name":"Drooling Face","emoji":"🤤"},
{"name":"Sleeping Face","emoji":"😴"},
{"name":"Face With Medical Mask","emoji":"😷"},
{"name":"Face With Thermometer","emoji":"🤒"},
{"name":"Face With Head-Bandage","emoji":"🤕"},
{"name":"Nauseated Face","emoji":"🤢"},
{"name":"Face Vomiting","emoji":"🤮"},
{"name":"Sneezing Face","emoji":"🤧"},
{"name":"Hot Face","emoji":"🥵"},
{"name":"Cold Face","emoji":"🥶"},
{"name":"Woozy Face","emoji":"🥴"},
{"name":"Dizzy Face","emoji":"😵"},
{"name":"Exploding Head","emoji":"🤯"},
{"name":"Cowboy Hat Face","emoji":"🤠"},

{"name":"Partying Face","emoji":"🥳"},
{"name":"Smiling Face With Sunglasses","emoji":"😎"},
{"name":"Nerd Face","emoji":"🤓"},
{"name":"Face With Monocle","emoji":"🧐"},
{"name":"Confused Face","emoji":"😕"},
{"name":"Worried Face","emoji":"😟"},
{"name":"Slightly Frowning Face","emoji":"🙁"},
{"name":"Frowning Face","emoji":"☹"},
{"name":"Face With Open Mouth","emoji":"😮"},
{"name":"Hushed Face","emoji":"😯"},
{"name":"Astonished Face","emoji":"😲"},
{"name":"Flushed Face","emoji":"😳"},
{"name":"Pleading Face","emoji":"🥺"},
{"name":"Frowning Face With Open Mouth","emoji":"😦"},
{"name":"Anguished Face","emoji":"😧"},
{"name":"Fearful Face","emoji":"😨"},
{"name":"Anxious Face With Sweat","emoji":"😰"},
{"name":"Sad but Relieved Face","emoji":"😥"},
{"name":"Crying Face","emoji":"😢"},
{"name":"Loudly Crying Face","emoji":"😭"},
{"name":"Face Screaming in Fear","emoji":"😱"},
{"name":"Confounded Face","emoji":"😖"},
{"name":"Persevering Face","emoji":"😣"},
{"name":"Disappointed Face","emoji":"😞"},
{"name":"Downcast Face With Sweat","emoji":"😓"},
{"name":"Weary Face","emoji":"😩"},
{"name":"Tired Face","emoji":"😫"},
{"name":"Face With Steam From Nose","emoji":"😤"},
{"name":"Pouting Face","emoji":"😡"},
{"name":"Angry Face","emoji":"😠"},
{"name":"Face With Symbols on Mouth","emoji":"🤬"},
{"name":"Smiling Face With Horns","emoji":"😈"},
{"name":"Angry Face With Horns","emoji":"👿"},
{"name":"Skull","emoji":"💀"},
{"name":"Skull and Crossbones","emoji":"☠"},
{"name":"Pile of Poo","emoji":"💩"},
{"name":"Clown Face","emoji":"🤡"},
{"name":"Ogre","emoji":"👹"},
{"name":"Goblin","emoji":"👺"},
{"name":"Ghost","emoji":"👻"},
{"name":"Alien","emoji":"👽"},
{"name":"Alien Monster","emoji":"👾"},
{"name":"Robot","emoji":"🤖"},
{"name":"Grinning Cat","emoji":"😺"},
{"name":"Grinning Cat With Smiling Eyes","emoji":"😸"},
{"name":"Cat With Tears of Joy","emoji":"😹"},
{"name":"Smiling Cat With Heart-Eyes","emoji":"😻"},
{"name":"Cat With Wry Smile","emoji":"😼"},
{"name":"Kissing Cat","emoji":"😽"},
{"name":"Weary Cat","emoji":"🙀"},
{"name":"Crying Cat","emoji":"😿"},
{"name":"Pouting Cat","emoji":"😾"},
{"name":"Kiss Mark","emoji":"💋"},
{"name":"Waving Hand","emoji":"👋"},
{"name":"Raised Back of Hand","emoji":"🤚"},
{"name":"Hand With Fingers Splayed","emoji":"🖐"},
{"name":"Raised Hand","emoji":"✋"},
{"name":"Vulcan Salute","emoji":"🖖"},
{"name":"OK Hand","emoji":"👌"},
{"name":"Victory Hand","emoji":"✌"},
{"name":"Crossed Fingers","emoji":"🤞"},
{"name":"Love-You Gesture","emoji":"🤟"},
{"name":"Sign of the Horns","emoji":"🤘"},
{"name":"Call Me Hand","emoji":"🤙"},
{"name":"Backhand Index Pointing Left","emoji":"👈"},
{"name":"Backhand Index Pointing Right","emoji":"👉"},
{"name":"Backhand Index Pointing Up","emoji":"👆"},
{"name":"Middle Finger","emoji":"🖕"},
{"name":"Backhand Index Pointing Down","emoji":"👇"},
{"name":"Index Pointing Up","emoji":"☝"},
{"name":"Thumbs Up","emoji":"👍"},
{"name":"Thumbs Down","emoji":"👎"},
{"name":"Raised Fist","emoji":"✊"},
{"name":"Oncoming Fist","emoji":"👊"},
{"name":"Left-Facing Fist","emoji":"🤛"},
{"name":"Right-Facing Fist","emoji":"🤜"},
{"name":"Clapping Hands","emoji":"👏"},
{"name":"Raising Hands","emoji":"🙌"},
{"name":"Open Hands","emoji":"👐"},
{"name":"Palms Up Together","emoji":"🤲"},
{"name":"Handshake","emoji":"🤝"},
{"name":"Folded Hands","emoji":"🙏"},
{"name":"Writing Hand","emoji":"✍"},
{"name":"Nail Polish","emoji":"💅"},
{"name":"Selfie","emoji":"🤳"},
{"name":"Flexed Biceps","emoji":"💪"},
{"name":"Leg","emoji":"🦵"},
{"name":"Foot","emoji":"🦶"},
{"name":"Ear","emoji":"👂"},
{"name":"Nose","emoji":"👃"},
{"name":"Brain","emoji":"🧠"},
{"name":"Tooth","emoji":"🦷"},
{"name":"Bone","emoji":"🦴"},
{"name":"Eyes","emoji":"👀"},
{"name":"Eye","emoji":"👁"},
{"name":"Tongue","emoji":"👅"},
{"name":"Mouth","emoji":"👄"},
{"name":"Baby","emoji":"👶"},
{"name":"Child","emoji":"🧒"},
{"name":"Boy","emoji":"👦"},
{"name":"Girl","emoji":"👧"},
{"name":"Person","emoji":"🧑"},
{"name":"Person: Blond Hair","emoji":"👱"},
{"name":"Man","emoji":"👨"},
{"name":"Man: Beard","emoji":"🧔"},
{"name":"Man: Red Hair","emoji":"👨‍🦰"},
{"name":"Man: Curly Hair","emoji":"👨‍🦱"},
{"name":"Man: White Hair","emoji":"👨‍🦳"},
{"name":"Man: Bald","emoji":"👨‍🦲"},
{"name":"Woman","emoji":"👩"},
{"name":"Woman: Red Hair","emoji":"👩‍🦰"},
{"name":"Woman: Curly Hair","emoji":"👩‍🦱"},
{"name":"Woman: White Hair","emoji":"👩‍🦳"},
{"name":"Woman: Bald","emoji":"👩‍🦲"},
{"name":"Woman: Blond Hair","emoji":"👱‍♀️"},
{"name":"Man: Blond Hair","emoji":"👱‍♂️"},
{"name":"Older Person","emoji":"🧓"},
{"name":"Old Man","emoji":"👴"},
{"name":"Old Woman","emoji":"👵"},
{"name":"Person Frowning","emoji":"🙍"},
{"name":"Man Frowning","emoji":"🙍‍♂️"},
{"name":"Woman Frowning","emoji":"🙍‍♀️"},
{"name":"Person Pouting","emoji":"🙎"},
{"name":"Man Pouting","emoji":"🙎‍♂️"},
{"name":"Woman Pouting","emoji":"🙎‍♀️"},
{"name":"Person Gesturing No","emoji":"🙅"},
{"name":"Man Gesturing No","emoji":"🙅‍♂️"},
{"name":"Woman Gesturing No","emoji":"🙅‍♀️"},
{"name":"Person Gesturing OK","emoji":"🙆"},
{"name":"Man Gesturing OK","emoji":"🙆‍♂️"},
{"name":"Woman Gesturing OK","emoji":"🙆‍♀️"},
{"name":"Person Tipping Hand","emoji":"💁"},
{"name":"Man Tipping Hand","emoji":"💁‍♂️"},
{"name":"Woman Tipping Hand","emoji":"💁‍♀️"},
{"name":"Person Raising Hand","emoji":"🙋"},
{"name":"Man Raising Hand","emoji":"🙋‍♂️"},
{"name":"Woman Raising Hand","emoji":"🙋‍♀️"},
{"name":"Person Bowing","emoji":"🙇"},
{"name":"Man Bowing","emoji":"🙇‍♂️"},
{"name":"Woman Bowing","emoji":"🙇‍♀️"},
{"name":"Person Facepalming","emoji":"🤦"},
{"name":"Man Facepalming","emoji":"🤦‍♂️"},
{"name":"Woman Facepalming","emoji":"🤦‍♀️"},
{"name":"Person Shrugging","emoji":"🤷"},
{"name":"Man Shrugging","emoji":"🤷‍♂️"},
{"name":"Woman Shrugging","emoji":"🤷‍♀️"},
{"name":"Man Health Worker","emoji":"👨‍⚕️"},
{"name":"Woman Health Worker","emoji":"👩‍⚕️"},
{"name":"Man Student","emoji":"👨‍🎓"},
{"name":"Woman Student","emoji":"👩‍🎓"},
{"name":"Man Teacher","emoji":"👨‍🏫"},
{"name":"Woman Teacher","emoji":"👩‍🏫"},
{"name":"Man Judge","emoji":"👨‍⚖️"},
{"name":"Woman Judge","emoji":"👩‍⚖️"},
{"name":"Man Farmer","emoji":"👨‍🌾"},
{"name":"Woman Farmer","emoji":"👩‍🌾"},
{"name":"Man Cook","emoji":"👨‍🍳"},
{"name":"Woman Cook","emoji":"👩‍🍳"},
{"name":"Man Mechanic","emoji":"👨‍🔧"},
{"name":"Woman Mechanic","emoji":"👩‍🔧"},
{"name":"Man Factory Worker","emoji":"👨‍🏭"},
{"name":"Woman Factory Worker","emoji":"👩‍🏭"},
{"name":"Man Office Worker","emoji":"👨‍💼"},
{"name":"Woman Office Worker","emoji":"👩‍💼"},
{"name":"Man Scientist","emoji":"👨‍🔬"},
{"name":"Woman Scientist","emoji":"👩‍🔬"},
{"name":"Man Technologist","emoji":"👨‍💻"},
{"name":"Woman Technologist","emoji":"👩‍💻"},
{"name":"Man Singer","emoji":"👨‍🎤"},
{"name":"Woman Singer","emoji":"👩‍🎤"},
{"name":"Man Artist","emoji":"👨‍🎨"},
{"name":"Woman Artist","emoji":"👩‍🎨"},
{"name":"Man Pilot","emoji":"👨‍✈️"},
{"name":"Woman Pilot","emoji":"👩‍✈️"},
{"name":"Man Astronaut","emoji":"👨‍🚀"},
{"name":"Woman Astronaut","emoji":"👩‍🚀"},
{"name":"Man Firefighter","emoji":"👨‍🚒"},
{"name":"Woman Firefighter","emoji":"👩‍🚒"},
{"name":"Police Officer","emoji":"👮"},
{"name":"Man Police Officer","emoji":"👮‍♂️"},
{"name":"Woman Police Officer","emoji":"👮‍♀️"},
{"name":"Detective","emoji":"🕵"},
{"name":"Man Detective","emoji":"🕵️‍♂️"},
{"name":"Woman Detective","emoji":"🕵️‍♀️"},
{"name":"Guard","emoji":"💂"},
{"name":"Man Guard","emoji":"💂‍♂️"},
{"name":"Woman Guard","emoji":"💂‍♀️"},
{"name":"Construction Worker","emoji":"👷"},
{"name":"Man Construction Worker","emoji":"👷‍♂️"},
{"name":"Woman Construction Worker","emoji":"👷‍♀️"},
{"name":"Prince","emoji":"🤴"},
{"name":"Princess","emoji":"👸"},
{"name":"Person Wearing Turban","emoji":"👳"},
{"name":"Man Wearing Turban","emoji":"👳‍♂️"},
{"name":"Woman Wearing Turban","emoji":"👳‍♀️"},
{"name":"Man With Skullcap","emoji":"👲"},
{"name":"Woman With Headscarf","emoji":"🧕"},
{"name":"Man in Tuxedo","emoji":"🤵"},
{"name":"Bride With Veil","emoji":"👰"},
{"name":"Pregnant Woman","emoji":"🤰"},
{"name":"Breast-Feeding","emoji":"🤱"},
{"name":"Baby Angel","emoji":"👼"},
{"name":"Santa Claus","emoji":"🎅"},
{"name":"Mrs. Claus","emoji":"🤶"},
{"name":"Superhero","emoji":"🦸"},
{"name":"Man Superhero","emoji":"🦸‍♂️"},
{"name":"Woman Superhero","emoji":"🦸‍♀️"},
{"name":"Supervillain","emoji":"🦹"},
{"name":"Man Supervillain","emoji":"🦹‍♂️"},
{"name":"Woman Supervillain","emoji":"🦹‍♀️"},
{"name":"Mage","emoji":"🧙"},
{"name":"Man Mage","emoji":"🧙‍♂️"},
{"name":"Woman Mage","emoji":"🧙‍♀️"},
{"name":"Fairy","emoji":"🧚"},
{"name":"Man Fairy","emoji":"🧚‍♂️"},
{"name":"Woman Fairy","emoji":"🧚‍♀️"},
{"name":"Vampire","emoji":"🧛"},
{"name":"Man Vampire","emoji":"🧛‍♂️"},
{"name":"Woman Vampire","emoji":"🧛‍♀️"},
{"name":"Merperson","emoji":"🧜"},
{"name":"Merman","emoji":"🧜‍♂️"},
{"name":"Mermaid","emoji":"🧜‍♀️"},
{"name":"Elf","emoji":"🧝"},
{"name":"Man Elf","emoji":"🧝‍♂️"},
{"name":"Woman Elf","emoji":"🧝‍♀️"},
{"name":"Genie","emoji":"🧞"},
{"name":"Man Genie","emoji":"🧞‍♂️"},
{"name":"Woman Genie","emoji":"🧞‍♀️"},
{"name":"Zombie","emoji":"🧟"},
{"name":"Man Zombie","emoji":"🧟‍♂️"},
{"name":"Woman Zombie","emoji":"🧟‍♀️"},
{"name":"Person Getting Massage","emoji":"💆"},
{"name":"Man Getting Massage","emoji":"💆‍♂️"},
{"name":"Woman Getting Massage","emoji":"💆‍♀️"},
{"name":"Person Getting Haircut","emoji":"💇"},
{"name":"Man Getting Haircut","emoji":"💇‍♂️"},
{"name":"Woman Getting Haircut","emoji":"💇‍♀️"},
{"name":"Person Walking","emoji":"🚶"},
{"name":"Man Walking","emoji":"🚶‍♂️"},
{"name":"Woman Walking","emoji":"🚶‍♀️"},
{"name":"Person Running","emoji":"🏃"},
{"name":"Man Running","emoji":"🏃‍♂️"},
{"name":"Woman Running","emoji":"🏃‍♀️"},
{"name":"Woman Dancing","emoji":"💃"},
{"name":"Man Dancing","emoji":"🕺"},
{"name":"Man in Suit Levitating","emoji":"🕴"},
{"name":"People With Bunny Ears","emoji":"👯"},
{"name":"Men With Bunny Ears","emoji":"👯‍♂️"},
{"name":"Women With Bunny Ears","emoji":"👯‍♀️"},
{"name":"Person in Steamy Room","emoji":"🧖"},
{"name":"Man in Steamy Room","emoji":"🧖‍♂️"},
{"name":"Woman in Steamy Room","emoji":"🧖‍♀️"},
{"name":"Person in Lotus Position","emoji":"🧘"},
{"name":"Women Holding Hands","emoji":"👭"},
{"name":"Woman and Man Holding Hands","emoji":"👫"},
{"name":"Men Holding Hands","emoji":"👬"},
{"name":"Kiss","emoji":"💏"},
{"name":"Kiss: Man, Man","emoji":"👨‍❤️‍💋‍👨"},
{"name":"Kiss: Woman, Woman","emoji":"👩‍❤️‍💋‍👩"},
{"name":"Couple With Heart","emoji":"💑"},
{"name":"Couple With Heart: Man, Man","emoji":"👨‍❤️‍👨"},
{"name":"Couple With Heart: Woman, Woman","emoji":"👩‍❤️‍👩"},
{"name":"Family","emoji":"👪"},
{"name":"Family: Man, Woman, Boy","emoji":"👨‍👩‍👦"},
{"name":"Family: Man, Woman, Girl","emoji":"👨‍👩‍👧"},
{"name":"Family: Man, Woman, Girl, Boy","emoji":"👨‍👩‍👧‍👦"},
{"name":"Family: Man, Woman, Boy, Boy","emoji":"👨‍👩‍👦‍👦"},
{"name":"Family: Man, Woman, Girl, Girl","emoji":"👨‍👩‍👧‍👧"},
{"name":"Family: Man, Man, Boy","emoji":"👨‍👨‍👦"},
{"name":"Family: Man, Man, Girl","emoji":"👨‍👨‍👧"},
{"name":"Family: Man, Man, Girl, Boy","emoji":"👨‍👨‍👧‍👦"},
{"name":"Family: Man, Man, Boy, Boy","emoji":"👨‍👨‍👦‍👦"},
{"name":"Family: Man, Man, Girl, Girl","emoji":"👨‍👨‍👧‍👧"},
{"name":"Family: Woman, Woman, Boy","emoji":"👩‍👩‍👦"},
{"name":"Family: Woman, Woman, Girl","emoji":"👩‍👩‍👧"},
{"name":"Family: Woman, Woman, Girl, Boy","emoji":"👩‍👩‍👧‍👦"},
{"name":"Family: Woman, Woman, Boy, Boy","emoji":"👩‍👩‍👦‍👦"},
{"name":"Family: Woman, Woman, Girl, Girl","emoji":"👩‍👩‍👧‍👧"},
{"name":"Family: Man, Boy","emoji":"👨‍👦"},
{"name":"Family: Man, Boy, Boy","emoji":"👨‍👦‍👦"},
{"name":"Family: Man, Girl","emoji":"👨‍👧"},
{"name":"Family: Man, Girl, Boy","emoji":"👨‍👧‍👦"},
{"name":"Family: Man, Girl, Girl","emoji":"👨‍👧‍👧"},
{"name":"Family: Woman, Boy","emoji":"👩‍👦"},
{"name":"Family: Woman, Boy, Boy","emoji":"👩‍👦‍👦"},
{"name":"Family: Woman, Girl","emoji":"👩‍👧"},
{"name":"Family: Woman, Girl, Boy","emoji":"👩‍👧‍👦"},
{"name":"Family: Woman, Girl, Girl","emoji":"👩‍👧‍👧"},
{"name":"Speaking Head","emoji":"🗣"},
{"name":"Bust in Silhouette","emoji":"👤"},
{"name":"Busts in Silhouette","emoji":"👥"},
{"name":"Footprints","emoji":"👣"},
{"name":"Luggage","emoji":"🧳"},
{"name":"Closed Umbrella","emoji":"🌂"},
{"name":"Umbrella","emoji":"☂"},
{"name":"Thread","emoji":"🧵"},
{"name":"Yarn","emoji":"🧶"},
{"name":"Glasses","emoji":"👓"},
{"name":"Sunglasses","emoji":"🕶"},
{"name":"Goggles","emoji":"🥽"},
{"name":"Lab Coat","emoji":"🥼"},
{"name":"Necktie","emoji":"👔"},
{"name":"T-Shirt","emoji":"👕"},
{"name":"Jeans","emoji":"👖"},
{"name":"Scarf","emoji":"🧣"},
{"name":"Gloves","emoji":"🧤"},
{"name":"Coat","emoji":"🧥"},
{"name":"Socks","emoji":"🧦"},
{"name":"Dress","emoji":"👗"},
{"name":"Kimono","emoji":"👘"},
{"name":"Bikini","emoji":"👙"},
{"name":"Woman’s Clothes","emoji":"👚"},
{"name":"Purse","emoji":"👛"},
{"name":"Handbag","emoji":"👜"},
{"name":"Clutch Bag","emoji":"👝"},
{"name":"Backpack","emoji":"🎒"},
{"name":"Man’s Shoe","emoji":"👞"},
{"name":"Running Shoe","emoji":"👟"},
{"name":"Hiking Boot","emoji":"🥾"},
{"name":"Flat Shoe","emoji":"🥿"},
{"name":"High-Heeled Shoe","emoji":"👠"},
{"name":"Woman’s Sandal","emoji":"👡"},
{"name":"Woman’s Boot","emoji":"👢"},
{"name":"Crown","emoji":"👑"},
{"name":"Woman’s Hat","emoji":"👒"},
{"name":"Top Hat","emoji":"🎩"},
{"name":"Graduation Cap","emoji":"🎓"},
{"name":"Billed Cap","emoji":"🧢"},
{"name":"Rescue Worker’s Helmet","emoji":"⛑"},
{"name":"Lipstick","emoji":"💄"},
{"name":"Ring","emoji":"💍"},
{"name":"Briefcase","emoji":"💼"},
{"name":"Grinning Face","emoji":"😀"},
{"name":"Grinning Face With Big Eyes","emoji":"😃"},
{"name":"Grinning Face With Smiling Eyes","emoji":"😄"},
{"name":"Beaming Face With Smiling Eyes","emoji":"😁"},
{"name":"Grinning Squinting Face","emoji":"😆"},
{"name":"Grinning Face With Sweat","emoji":"😅"},
{"name":"Rolling on the Floor Laughing","emoji":"🤣"},
{"name":"Face With Tears of Joy","emoji":"😂"},
{"name":"Slightly Smiling Face","emoji":"🙂"},
{"name":"Upside-Down Face","emoji":"🙃"},
{"name":"Winking Face","emoji":"😉"},
{"name":"Smiling Face With Smiling Eyes","emoji":"😊"},
{"name":"Smiling Face With Halo","emoji":"😇"},
{"name":"Smiling Face With Hearts","emoji":"🥰"},
{"name":"Smiling Face With Heart-Eyes","emoji":"😍"},
{"name":"Star-Struck","emoji":"🤩"},
{"name":"Face Blowing a Kiss","emoji":"😘"},
{"name":"Kissing Face","emoji":"😗"},
{"name":"Smiling Face","emoji":"☺"},
{"name":"Kissing Face With Closed Eyes","emoji":"😚"},
{"name":"Kissing Face With Smiling Eyes","emoji":"😙"},
{"name":"Face Savoring Food","emoji":"😋"},
{"name":"Face With Tongue","emoji":"😛"},
{"name":"Winking Face With Tongue","emoji":"😜"},
{"name":"Zany Face","emoji":"🤪"},
{"name":"Squinting Face With Tongue","emoji":"😝"},
{"name":"Money-Mouth Face","emoji":"🤑"},
{"name":"Hugging Face","emoji":"🤗"},
{"name":"Face With Hand Over Mouth","emoji":"🤭"},
{"name":"Shushing Face","emoji":"🤫"},
{"name":"Thinking Face","emoji":"🤔"},
{"name":"Zipper-Mouth Face","emoji":"🤐"},
{"name":"Face With Raised Eyebrow","emoji":"🤨"},
{"name":"Neutral Face","emoji":"😐"},
{"name":"Expressionless Face","emoji":"😑"},
{"name":"Face Without Mouth","emoji":"😶"},
{"name":"Smirking Face","emoji":"😏"},
{"name":"Unamused Face","emoji":"😒"},
{"name":"Face With Rolling Eyes","emoji":"🙄"},
{"name":"Grimacing Face","emoji":"😬"},
{"name":"Lying Face","emoji":"🤥"},
{"name":"Relieved Face","emoji":"😌"},
{"name":"Pensive Face","emoji":"😔"},
{"name":"Sleepy Face","emoji":"😪"},
{"name":"Drooling Face","emoji":"🤤"},
{"name":"Sleeping Face","emoji":"😴"},
{"name":"Face With Medical Mask","emoji":"😷"},
{"name":"Face With Thermometer","emoji":"🤒"},
{"name":"Face With Head-Bandage","emoji":"🤕"},
{"name":"Nauseated Face","emoji":"🤢"},
{"name":"Face Vomiting","emoji":"🤮"},
{"name":"Sneezing Face","emoji":"🤧"},
{"name":"Hot Face","emoji":"🥵"},
{"name":"Cold Face","emoji":"🥶"},
{"name":"Woozy Face","emoji":"🥴"},
{"name":"Dizzy Face","emoji":"😵"},
{"name":"Exploding Head","emoji":"🤯"},
{"name":"Cowboy Hat Face","emoji":"🤠"},

{"name":"Partying Face","emoji":"🥳"},
{"name":"Smiling Face With Sunglasses","emoji":"😎"},
{"name":"Nerd Face","emoji":"🤓"},
{"name":"Face With Monocle","emoji":"🧐"},
{"name":"Confused Face","emoji":"😕"},
{"name":"Worried Face","emoji":"😟"},
{"name":"Slightly Frowning Face","emoji":"🙁"},
{"name":"Frowning Face","emoji":"☹"},
{"name":"Face With Open Mouth","emoji":"😮"},
{"name":"Hushed Face","emoji":"😯"},
{"name":"Astonished Face","emoji":"😲"},
{"name":"Flushed Face","emoji":"😳"},
{"name":"Pleading Face","emoji":"🥺"},
{"name":"Frowning Face With Open Mouth","emoji":"😦"},
{"name":"Anguished Face","emoji":"😧"},
{"name":"Fearful Face","emoji":"😨"},
{"name":"Anxious Face With Sweat","emoji":"😰"},
{"name":"Sad but Relieved Face","emoji":"😥"},
{"name":"Crying Face","emoji":"😢"},
{"name":"Loudly Crying Face","emoji":"😭"},
{"name":"Face Screaming in Fear","emoji":"😱"},
{"name":"Confounded Face","emoji":"😖"},
{"name":"Persevering Face","emoji":"😣"},
{"name":"Disappointed Face","emoji":"😞"},
{"name":"Downcast Face With Sweat","emoji":"😓"},
{"name":"Weary Face","emoji":"😩"},
{"name":"Tired Face","emoji":"😫"},
{"name":"Face With Steam From Nose","emoji":"😤"},
{"name":"Pouting Face","emoji":"😡"},
{"name":"Angry Face","emoji":"😠"},
{"name":"Face With Symbols on Mouth","emoji":"🤬"},
{"name":"Smiling Face With Horns","emoji":"😈"},
{"name":"Angry Face With Horns","emoji":"👿"},
{"name":"Skull","emoji":"💀"},
{"name":"Skull and Crossbones","emoji":"☠"},
{"name":"Pile of Poo","emoji":"💩"},
{"name":"Clown Face","emoji":"🤡"},
{"name":"Ogre","emoji":"👹"},
{"name":"Goblin","emoji":"👺"},
{"name":"Ghost","emoji":"👻"},
{"name":"Alien","emoji":"👽"},
{"name":"Alien Monster","emoji":"👾"},
{"name":"Robot","emoji":"🤖"},
{"name":"Grinning Cat","emoji":"😺"},
{"name":"Grinning Cat With Smiling Eyes","emoji":"😸"},
{"name":"Cat With Tears of Joy","emoji":"😹"},
{"name":"Smiling Cat With Heart-Eyes","emoji":"😻"},
{"name":"Cat With Wry Smile","emoji":"😼"},
{"name":"Kissing Cat","emoji":"😽"},
{"name":"Weary Cat","emoji":"🙀"},
{"name":"Crying Cat","emoji":"😿"},
{"name":"Pouting Cat","emoji":"😾"},
{"name":"Kiss Mark","emoji":"💋"},
{"name":"Waving Hand","emoji":"👋"},
{"name":"Raised Back of Hand","emoji":"🤚"},
{"name":"Hand With Fingers Splayed","emoji":"🖐"},
{"name":"Raised Hand","emoji":"✋"},
{"name":"Vulcan Salute","emoji":"🖖"},
{"name":"OK Hand","emoji":"👌"},
{"name":"Victory Hand","emoji":"✌"},
{"name":"Crossed Fingers","emoji":"🤞"},
{"name":"Love-You Gesture","emoji":"🤟"},
{"name":"Sign of the Horns","emoji":"🤘"},
{"name":"Call Me Hand","emoji":"🤙"},
{"name":"Backhand Index Pointing Left","emoji":"👈"},
{"name":"Backhand Index Pointing Right","emoji":"👉"},
{"name":"Backhand Index Pointing Up","emoji":"👆"},
{"name":"Middle Finger","emoji":"🖕"},
{"name":"Backhand Index Pointing Down","emoji":"👇"},
{"name":"Index Pointing Up","emoji":"☝"},
{"name":"Thumbs Up","emoji":"👍"},
{"name":"Thumbs Down","emoji":"👎"},
{"name":"Raised Fist","emoji":"✊"},
{"name":"Oncoming Fist","emoji":"👊"},
{"name":"Left-Facing Fist","emoji":"🤛"},
{"name":"Right-Facing Fist","emoji":"🤜"},
{"name":"Clapping Hands","emoji":"👏"},
{"name":"Raising Hands","emoji":"🙌"},
{"name":"Open Hands","emoji":"👐"},
{"name":"Palms Up Together","emoji":"🤲"},
{"name":"Handshake","emoji":"🤝"},
{"name":"Folded Hands","emoji":"🙏"},
{"name":"Writing Hand","emoji":"✍"},
{"name":"Nail Polish","emoji":"💅"},
{"name":"Selfie","emoji":"🤳"},
{"name":"Flexed Biceps","emoji":"💪"},
{"name":"Leg","emoji":"🦵"},
{"name":"Foot","emoji":"🦶"},
{"name":"Ear","emoji":"👂"},
{"name":"Nose","emoji":"👃"},
{"name":"Brain","emoji":"🧠"},
{"name":"Tooth","emoji":"🦷"},
{"name":"Bone","emoji":"🦴"},
{"name":"Eyes","emoji":"👀"},
{"name":"Eye","emoji":"👁"},
{"name":"Tongue","emoji":"👅"},
{"name":"Mouth","emoji":"👄"},
{"name":"Baby","emoji":"👶"},
{"name":"Child","emoji":"🧒"},
{"name":"Boy","emoji":"👦"},
{"name":"Girl","emoji":"👧"},
{"name":"Person","emoji":"🧑"},
{"name":"Person: Blond Hair","emoji":"👱"},
{"name":"Man","emoji":"👨"},
{"name":"Man: Beard","emoji":"🧔"},
{"name":"Man: Red Hair","emoji":"👨‍🦰"},
{"name":"Man: Curly Hair","emoji":"👨‍🦱"},
{"name":"Man: White Hair","emoji":"👨‍🦳"},
{"name":"Man: Bald","emoji":"👨‍🦲"},
{"name":"Woman","emoji":"👩"},
{"name":"Woman: Red Hair","emoji":"👩‍🦰"},
{"name":"Woman: Curly Hair","emoji":"👩‍🦱"},
{"name":"Woman: White Hair","emoji":"👩‍🦳"},
{"name":"Woman: Bald","emoji":"👩‍🦲"},
{"name":"Woman: Blond Hair","emoji":"👱‍♀️"},
{"name":"Man: Blond Hair","emoji":"👱‍♂️"},
{"name":"Older Person","emoji":"🧓"},
{"name":"Old Man","emoji":"👴"},
{"name":"Old Woman","emoji":"👵"},
{"name":"Person Frowning","emoji":"🙍"},
{"name":"Man Frowning","emoji":"🙍‍♂️"},
{"name":"Woman Frowning","emoji":"🙍‍♀️"},
{"name":"Person Pouting","emoji":"🙎"},
{"name":"Man Pouting","emoji":"🙎‍♂️"},
{"name":"Woman Pouting","emoji":"🙎‍♀️"},
{"name":"Person Gesturing No","emoji":"🙅"},
{"name":"Man Gesturing No","emoji":"🙅‍♂️"},
{"name":"Woman Gesturing No","emoji":"🙅‍♀️"},
{"name":"Person Gesturing OK","emoji":"🙆"},
{"name":"Man Gesturing OK","emoji":"🙆‍♂️"},
{"name":"Woman Gesturing OK","emoji":"🙆‍♀️"},
{"name":"Person Tipping Hand","emoji":"💁"},
{"name":"Man Tipping Hand","emoji":"💁‍♂️"},
{"name":"Woman Tipping Hand","emoji":"💁‍♀️"},
{"name":"Person Raising Hand","emoji":"🙋"},
{"name":"Man Raising Hand","emoji":"🙋‍♂️"},
{"name":"Woman Raising Hand","emoji":"🙋‍♀️"},
{"name":"Person Bowing","emoji":"🙇"},
{"name":"Man Bowing","emoji":"🙇‍♂️"},
{"name":"Woman Bowing","emoji":"🙇‍♀️"},
{"name":"Person Facepalming","emoji":"🤦"},
{"name":"Man Facepalming","emoji":"🤦‍♂️"},
{"name":"Woman Facepalming","emoji":"🤦‍♀️"},
{"name":"Person Shrugging","emoji":"🤷"},
{"name":"Man Shrugging","emoji":"🤷‍♂️"},
{"name":"Woman Shrugging","emoji":"🤷‍♀️"},
{"name":"Man Health Worker","emoji":"👨‍⚕️"},
{"name":"Woman Health Worker","emoji":"👩‍⚕️"},
{"name":"Man Student","emoji":"👨‍🎓"},
{"name":"Woman Student","emoji":"👩‍🎓"},
{"name":"Man Teacher","emoji":"👨‍🏫"},
{"name":"Woman Teacher","emoji":"👩‍🏫"},
{"name":"Man Judge","emoji":"👨‍⚖️"},
{"name":"Woman Judge","emoji":"👩‍⚖️"},
{"name":"Man Farmer","emoji":"👨‍🌾"},
{"name":"Woman Farmer","emoji":"👩‍🌾"},
{"name":"Man Cook","emoji":"👨‍🍳"},
{"name":"Woman Cook","emoji":"👩‍🍳"},
{"name":"Man Mechanic","emoji":"👨‍🔧"},
{"name":"Woman Mechanic","emoji":"👩‍🔧"},
{"name":"Man Factory Worker","emoji":"👨‍🏭"},
{"name":"Woman Factory Worker","emoji":"👩‍🏭"},
{"name":"Man Office Worker","emoji":"👨‍💼"},
{"name":"Woman Office Worker","emoji":"👩‍💼"},
{"name":"Man Scientist","emoji":"👨‍🔬"},
{"name":"Woman Scientist","emoji":"👩‍🔬"},
{"name":"Man Technologist","emoji":"👨‍💻"},
{"name":"Woman Technologist","emoji":"👩‍💻"},
{"name":"Man Singer","emoji":"👨‍🎤"},
{"name":"Woman Singer","emoji":"👩‍🎤"},
{"name":"Man Artist","emoji":"👨‍🎨"},
{"name":"Woman Artist","emoji":"👩‍🎨"},
{"name":"Man Pilot","emoji":"👨‍✈️"},
{"name":"Woman Pilot","emoji":"👩‍✈️"},
{"name":"Man Astronaut","emoji":"👨‍🚀"},
{"name":"Woman Astronaut","emoji":"👩‍🚀"},
{"name":"Man Firefighter","emoji":"👨‍🚒"},
{"name":"Woman Firefighter","emoji":"👩‍🚒"},
{"name":"Police Officer","emoji":"👮"},
{"name":"Man Police Officer","emoji":"👮‍♂️"},
{"name":"Woman Police Officer","emoji":"👮‍♀️"},
{"name":"Detective","emoji":"🕵"},
{"name":"Man Detective","emoji":"🕵️‍♂️"},
{"name":"Woman Detective","emoji":"🕵️‍♀️"},
{"name":"Guard","emoji":"💂"},
{"name":"Man Guard","emoji":"💂‍♂️"},
{"name":"Woman Guard","emoji":"💂‍♀️"},
{"name":"Construction Worker","emoji":"👷"},
{"name":"Man Construction Worker","emoji":"👷‍♂️"},
{"name":"Woman Construction Worker","emoji":"👷‍♀️"},
{"name":"Prince","emoji":"🤴"},
{"name":"Princess","emoji":"👸"},
{"name":"Person Wearing Turban","emoji":"👳"},
{"name":"Man Wearing Turban","emoji":"👳‍♂️"},
{"name":"Woman Wearing Turban","emoji":"👳‍♀️"},
{"name":"Man With Skullcap","emoji":"👲"},
{"name":"Woman With Headscarf","emoji":"🧕"},
{"name":"Man in Tuxedo","emoji":"🤵"},
{"name":"Bride With Veil","emoji":"👰"},
{"name":"Pregnant Woman","emoji":"🤰"},
{"name":"Breast-Feeding","emoji":"🤱"},
{"name":"Baby Angel","emoji":"👼"},
{"name":"Santa Claus","emoji":"🎅"},
{"name":"Mrs. Claus","emoji":"🤶"},
{"name":"Superhero","emoji":"🦸"},
{"name":"Man Superhero","emoji":"🦸‍♂️"},
{"name":"Woman Superhero","emoji":"🦸‍♀️"},
{"name":"Supervillain","emoji":"🦹"},
{"name":"Man Supervillain","emoji":"🦹‍♂️"},
{"name":"Woman Supervillain","emoji":"🦹‍♀️"},
{"name":"Mage","emoji":"🧙"},
{"name":"Man Mage","emoji":"🧙‍♂️"},
{"name":"Woman Mage","emoji":"🧙‍♀️"},
{"name":"Fairy","emoji":"🧚"},
{"name":"Man Fairy","emoji":"🧚‍♂️"},
{"name":"Woman Fairy","emoji":"🧚‍♀️"},
{"name":"Vampire","emoji":"🧛"},
{"name":"Man Vampire","emoji":"🧛‍♂️"},
{"name":"Woman Vampire","emoji":"🧛‍♀️"},
{"name":"Merperson","emoji":"🧜"},
{"name":"Merman","emoji":"🧜‍♂️"},
{"name":"Mermaid","emoji":"🧜‍♀️"},
{"name":"Elf","emoji":"🧝"},
{"name":"Man Elf","emoji":"🧝‍♂️"},
{"name":"Woman Elf","emoji":"🧝‍♀️"},
{"name":"Genie","emoji":"🧞"},
{"name":"Man Genie","emoji":"🧞‍♂️"},
{"name":"Woman Genie","emoji":"🧞‍♀️"},
{"name":"Zombie","emoji":"🧟"},
{"name":"Man Zombie","emoji":"🧟‍♂️"},
{"name":"Woman Zombie","emoji":"🧟‍♀️"},
{"name":"Person Getting Massage","emoji":"💆"},
{"name":"Man Getting Massage","emoji":"💆‍♂️"},
{"name":"Woman Getting Massage","emoji":"💆‍♀️"},
{"name":"Person Getting Haircut","emoji":"💇"},
{"name":"Man Getting Haircut","emoji":"💇‍♂️"},
{"name":"Woman Getting Haircut","emoji":"💇‍♀️"},
{"name":"Person Walking","emoji":"🚶"},
{"name":"Man Walking","emoji":"🚶‍♂️"},
{"name":"Woman Walking","emoji":"🚶‍♀️"},
{"name":"Person Running","emoji":"🏃"},
{"name":"Man Running","emoji":"🏃‍♂️"},
{"name":"Woman Running","emoji":"🏃‍♀️"},
{"name":"Woman Dancing","emoji":"💃"},
{"name":"Man Dancing","emoji":"🕺"},
{"name":"Man in Suit Levitating","emoji":"🕴"},
{"name":"People With Bunny Ears","emoji":"👯"},
{"name":"Men With Bunny Ears","emoji":"👯‍♂️"},
{"name":"Women With Bunny Ears","emoji":"👯‍♀️"},
{"name":"Person in Steamy Room","emoji":"🧖"},
{"name":"Man in Steamy Room","emoji":"🧖‍♂️"},
{"name":"Woman in Steamy Room","emoji":"🧖‍♀️"},
{"name":"Person in Lotus Position","emoji":"🧘"},
{"name":"Women Holding Hands","emoji":"👭"},
{"name":"Woman and Man Holding Hands","emoji":"👫"},
{"name":"Men Holding Hands","emoji":"👬"},
{"name":"Kiss","emoji":"💏"},
{"name":"Kiss: Man, Man","emoji":"👨‍❤️‍💋‍👨"},
{"name":"Kiss: Woman, Woman","emoji":"👩‍❤️‍💋‍👩"},
{"name":"Couple With Heart","emoji":"💑"},
{"name":"Couple With Heart: Man, Man","emoji":"👨‍❤️‍👨"},
{"name":"Couple With Heart: Woman, Woman","emoji":"👩‍❤️‍👩"},
{"name":"Family","emoji":"👪"},
{"name":"Family: Man, Woman, Boy","emoji":"👨‍👩‍👦"},
{"name":"Family: Man, Woman, Girl","emoji":"👨‍👩‍👧"},
{"name":"Family: Man, Woman, Girl, Boy","emoji":"👨‍👩‍👧‍👦"},
{"name":"Family: Man, Woman, Boy, Boy","emoji":"👨‍👩‍👦‍👦"},
{"name":"Family: Man, Woman, Girl, Girl","emoji":"👨‍👩‍👧‍👧"},
{"name":"Family: Man, Man, Boy","emoji":"👨‍👨‍👦"},
{"name":"Family: Man, Man, Girl","emoji":"👨‍👨‍👧"},
{"name":"Family: Man, Man, Girl, Boy","emoji":"👨‍👨‍👧‍👦"},
{"name":"Family: Man, Man, Boy, Boy","emoji":"👨‍👨‍👦‍👦"},
{"name":"Family: Man, Man, Girl, Girl","emoji":"👨‍👨‍👧‍👧"},
{"name":"Family: Woman, Woman, Boy","emoji":"👩‍👩‍👦"},
{"name":"Family: Woman, Woman, Girl","emoji":"👩‍👩‍👧"},
{"name":"Family: Woman, Woman, Girl, Boy","emoji":"👩‍👩‍👧‍👦"},
{"name":"Family: Woman, Woman, Boy, Boy","emoji":"👩‍👩‍👦‍👦"},
{"name":"Family: Woman, Woman, Girl, Girl","emoji":"👩‍👩‍👧‍👧"},
{"name":"Family: Man, Boy","emoji":"👨‍👦"},
{"name":"Family: Man, Boy, Boy","emoji":"👨‍👦‍👦"},
{"name":"Family: Man, Girl","emoji":"👨‍👧"},
{"name":"Family: Man, Girl, Boy","emoji":"👨‍👧‍👦"},
{"name":"Family: Man, Girl, Girl","emoji":"👨‍👧‍👧"},
{"name":"Family: Woman, Boy","emoji":"👩‍👦"},
{"name":"Family: Woman, Boy, Boy","emoji":"👩‍👦‍👦"},
{"name":"Family: Woman, Girl","emoji":"👩‍👧"},
{"name":"Family: Woman, Girl, Boy","emoji":"👩‍👧‍👦"},
{"name":"Family: Woman, Girl, Girl","emoji":"👩‍👧‍👧"},
{"name":"Speaking Head","emoji":"🗣"},
{"name":"Bust in Silhouette","emoji":"👤"},
{"name":"Busts in Silhouette","emoji":"👥"},
{"name":"Footprints","emoji":"👣"},
{"name":"Luggage","emoji":"🧳"},
{"name":"Closed Umbrella","emoji":"🌂"},
{"name":"Umbrella","emoji":"☂"},
{"name":"Thread","emoji":"🧵"},
{"name":"Yarn","emoji":"🧶"},
{"name":"Glasses","emoji":"👓"},
{"name":"Sunglasses","emoji":"🕶"},
{"name":"Goggles","emoji":"🥽"},
{"name":"Lab Coat","emoji":"🥼"},
{"name":"Necktie","emoji":"👔"},
{"name":"T-Shirt","emoji":"👕"},
{"name":"Jeans","emoji":"👖"},
{"name":"Scarf","emoji":"🧣"},
{"name":"Gloves","emoji":"🧤"},
{"name":"Coat","emoji":"🧥"},
{"name":"Socks","emoji":"🧦"},
{"name":"Dress","emoji":"👗"},
{"name":"Kimono","emoji":"👘"},
{"name":"Bikini","emoji":"👙"},
{"name":"Woman’s Clothes","emoji":"👚"},
{"name":"Purse","emoji":"👛"},
{"name":"Handbag","emoji":"👜"},
{"name":"Clutch Bag","emoji":"👝"},
{"name":"Backpack","emoji":"🎒"},
{"name":"Man’s Shoe","emoji":"👞"},
{"name":"Running Shoe","emoji":"👟"},
{"name":"Hiking Boot","emoji":"🥾"},
{"name":"Flat Shoe","emoji":"🥿"},
{"name":"High-Heeled Shoe","emoji":"👠"},
{"name":"Woman’s Sandal","emoji":"👡"},
{"name":"Woman’s Boot","emoji":"👢"},
{"name":"Crown","emoji":"👑"},
{"name":"Woman’s Hat","emoji":"👒"},
{"name":"Top Hat","emoji":"🎩"},
{"name":"Graduation Cap","emoji":"🎓"},
{"name":"Billed Cap","emoji":"🧢"},
{"name":"Rescue Worker’s Helmet","emoji":"⛑"},
{"name":"Lipstick","emoji":"💄"},
{"name":"Ring","emoji":"💍"},
{"name":"Briefcase","emoji":"💼"}
]